version: "3.7"

services:
  backend:
    container_name: backend
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - file-data:/app/public
      
  
  db:
    container_name: db
    image: postgres:13
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  file-data: